name = "zzo-Lite"
description = "Hugo blog theme with rich features."
license = "MIT"
licenselink = "https://github.com/vineelsai26/zzo-lite/blob/master/LICENSE.md"
tags = ["accessible", "multilingual", "responsive", "blog", "search", "simple", "light", "dark", "mobile", "gallery", "technical", "fast", "presentation"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "subtheme", "gallery", "technical", "fast", "presentation"]
min_version = "0.85.0"

[author]
  name = "Vineel Sai"
  homepage = "https://vineelsai.com"
